// AUTO-GENERATED by scripts/src/ingest-style-photos.ts — do not hand-edit.
// Rerun the script to regenerate after adding/updating source photo folders.
import type { Product, StyleHub } from "./mock-data";

export const INGESTED_PRODUCTS: Product[] = [
  {
    "id": "p-y2k-angel-graphic-cotton-cami-top",
    "name": "Angel Graphic Cotton Cami Top",
    "brand": "ZARA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 770,
    "mrp": 1220,
    "discountPercent": 37,
    "rating": 4.2,
    "reviewCount": 331,
    "images": [
      "/img/y2k-angel-graphic-cotton-cami-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Angel Graphic Cotton Cami Top — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-chic-striped-mesh-sweater",
    "name": "Chic Striped Mesh Sweater",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 501,
    "mrp": 840,
    "discountPercent": 40,
    "rating": 4.4,
    "reviewCount": 76,
    "images": [
      "/img/y2k-chic-striped-mesh-sweater.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Chic Striped Mesh Sweater — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-dianna-baggy-jeans",
    "name": "Dianna Baggy Jeans",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 485,
    "mrp": 870,
    "discountPercent": 44,
    "rating": 3.9,
    "reviewCount": 347,
    "images": [
      "/img/y2k-dianna-baggy-jeans.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Dianna Baggy Jeans — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-distressed-striped-sweater-with-scalf",
    "name": "Distressed Striped Sweater with Scalf",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 1034,
    "mrp": 1590,
    "discountPercent": 35,
    "rating": 4.4,
    "reviewCount": 325,
    "images": [
      "/img/y2k-distressed-striped-sweater-with-scalf.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Distressed Striped Sweater with Scalf — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-double-eyelet-belt",
    "name": "Double Eyelet Belt",
    "brand": "PULL&BEAR",
    "category": "Accessories",
    "subcategory": "Belts",
    "price": 697,
    "mrp": 1340,
    "discountPercent": 48,
    "rating": 4.3,
    "reviewCount": 180,
    "images": [
      "/img/y2k-double-eyelet-belt.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Double Eyelet Belt — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-fur-hooded-zip-up-knit-crop-cardigan",
    "name": "Fur Hooded Zip-up knit crop Cardigan",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 487,
    "mrp": 970,
    "discountPercent": 50,
    "rating": 4.2,
    "reviewCount": 117,
    "images": [
      "/img/y2k-fur-hooded-zip-up-knit-crop-cardigan.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Fur Hooded Zip-up knit crop Cardigan — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-graphic-oversized-hoodie",
    "name": "Graphic Oversized Hoodie",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 614,
    "mrp": 1200,
    "discountPercent": 49,
    "rating": 4.4,
    "reviewCount": 386,
    "images": [
      "/img/y2k-graphic-oversized-hoodie.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Graphic Oversized Hoodie — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-layered-drawstring-baggy-jorts",
    "name": "Layered DrawString Baggy Jorts",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 682,
    "mrp": 1050,
    "discountPercent": 35,
    "rating": 3.9,
    "reviewCount": 93,
    "images": [
      "/img/y2k-layered-drawstring-baggy-jorts.png"
    ],
    "colors": [
      "red"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Layered DrawString Baggy Jorts — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-loose-fit-striped-drop-shoulder-top",
    "name": "Loose Fit Striped Drop Shoulder Top",
    "brand": "VERO MODA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 913,
    "mrp": 1980,
    "discountPercent": 54,
    "rating": 3.9,
    "reviewCount": 222,
    "images": [
      "/img/y2k-loose-fit-striped-drop-shoulder-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Loose Fit Striped Drop Shoulder Top — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-lucky-graphic-tee",
    "name": "Lucky Graphic tee",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Tops",
    "price": 901,
    "mrp": 1500,
    "discountPercent": 40,
    "rating": 4.1,
    "reviewCount": 306,
    "images": [
      "/img/y2k-lucky-graphic-tee.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Lucky Graphic tee — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-mini-heart-hair-clip",
    "name": "Mini Heart Hair Clip",
    "brand": "FOREVER 21",
    "category": "Accessories",
    "subcategory": "Hair Accessories",
    "price": 614,
    "mrp": 890,
    "discountPercent": 31,
    "rating": 4,
    "reviewCount": 301,
    "images": [
      "/img/y2k-mini-heart-hair-clip.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Mini Heart Hair Clip — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-oversized-graphic-v-neck-jersey",
    "name": "Oversized Graphic V Neck Jersey",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 827,
    "mrp": 1330,
    "discountPercent": 38,
    "rating": 4.2,
    "reviewCount": 244,
    "images": [
      "/img/y2k-oversized-graphic-v-neck-jersey.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Oversized Graphic V Neck Jersey — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-ribbon-halter-crop-top",
    "name": "Ribbon Halter Crop Top",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Tops",
    "price": 502,
    "mrp": 1020,
    "discountPercent": 51,
    "rating": 4,
    "reviewCount": 205,
    "images": [
      "/img/y2k-ribbon-halter-crop-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Ribbon Halter Crop Top — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-rose-washed-bag-jeans",
    "name": "Rose Washed Bag Jeans",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 545,
    "mrp": 830,
    "discountPercent": 34,
    "rating": 4.3,
    "reviewCount": 232,
    "images": [
      "/img/y2k-rose-washed-bag-jeans.png"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Rose Washed Bag Jeans — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-sleek-snakeskin-belt",
    "name": "Sleek Snakeskin Belt",
    "brand": "H&M",
    "category": "Accessories",
    "subcategory": "Belts",
    "price": 299,
    "mrp": 580,
    "discountPercent": 48,
    "rating": 4.5,
    "reviewCount": 79,
    "images": [
      "/img/y2k-sleek-snakeskin-belt.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Sleek Snakeskin Belt — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-solic-pocketed-wide-fit-trousers",
    "name": "Solic Pocketed Wide Fit Trousers",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Trousers",
    "price": 805,
    "mrp": 1440,
    "discountPercent": 44,
    "rating": 4,
    "reviewCount": 220,
    "images": [
      "/img/y2k-solic-pocketed-wide-fit-trousers.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Solic Pocketed Wide Fit Trousers — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-vintage-washed-denim-shorts",
    "name": "Vintage Washed Denim Shorts",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Shorts",
    "price": 787,
    "mrp": 1640,
    "discountPercent": 52,
    "rating": 4.4,
    "reviewCount": 370,
    "images": [
      "/img/y2k-vintage-washed-denim-shorts.png"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Vintage Washed Denim Shorts — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-y2k-hair-claw-clip",
    "name": "Y2K Hair Claw Clip",
    "brand": "BERSHKA",
    "category": "Accessories",
    "subcategory": "Hair Accessories",
    "price": 456,
    "mrp": 890,
    "discountPercent": 49,
    "rating": 4.2,
    "reviewCount": 132,
    "images": [
      "/img/y2k-y2k-hair-claw-clip.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Y2K Hair Claw Clip — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-leilani-washed-jeans",
    "name": "leilani washed jeans",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 844,
    "mrp": 1480,
    "discountPercent": 43,
    "rating": 4.2,
    "reviewCount": 382,
    "images": [
      "/img/y2k-leilani-washed-jeans.png"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "leilani washed jeans — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-bow-detail-puff-blouse",
    "name": "Bow Detail Puff Blouse",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 417,
    "mrp": 720,
    "discountPercent": 42,
    "rating": 4.4,
    "reviewCount": 262,
    "images": [
      "/img/k-fashion-bow-detail-puff-blouse.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Bow Detail Puff Blouse — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-checked-halter-neck-peplum-top",
    "name": "Checked Halter Neck Peplum Top",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Tops",
    "price": 731,
    "mrp": 1310,
    "discountPercent": 44,
    "rating": 4.1,
    "reviewCount": 388,
    "images": [
      "/img/k-fashion-checked-halter-neck-peplum-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Checked Halter Neck Peplum Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-coffee-v-neck-sweatshirt",
    "name": "Coffee V-neck sweatshirt",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 465,
    "mrp": 930,
    "discountPercent": 50,
    "rating": 3.9,
    "reviewCount": 97,
    "images": [
      "/img/k-fashion-coffee-v-neck-sweatshirt.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Coffee V-neck sweatshirt — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-light-pink-top",
    "name": "Light Pink Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 374,
    "mrp": 610,
    "discountPercent": 39,
    "rating": 4.2,
    "reviewCount": 292,
    "images": [
      "/img/k-fashion-light-pink-top.png"
    ],
    "colors": [
      "pink"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Light Pink Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-miri-low-rise-straight-jeans",
    "name": "Miri Low Rise Straight Jeans",
    "brand": "BERSHKA",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 426,
    "mrp": 840,
    "discountPercent": 49,
    "rating": 4.5,
    "reviewCount": 255,
    "images": [
      "/img/k-fashion-miri-low-rise-straight-jeans.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Miri Low Rise Straight Jeans — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-olynn-low-rise-distressed-flared-jeans",
    "name": "Olynn Low-Rise Distressed Flared Jeans",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 562,
    "mrp": 1060,
    "discountPercent": 47,
    "rating": 4.5,
    "reviewCount": 291,
    "images": [
      "/img/k-fashion-olynn-low-rise-distressed-flared-jeans.png"
    ],
    "colors": [
      "red"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Olynn Low-Rise Distressed Flared Jeans — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-ribbed-square-neck-crepe-top",
    "name": "Ribbed Square Neck Crepe Top",
    "brand": "H&M",
    "category": "Women",
    "subcategory": "Tops",
    "price": 729,
    "mrp": 1100,
    "discountPercent": 34,
    "rating": 4.4,
    "reviewCount": 193,
    "images": [
      "/img/k-fashion-ribbed-square-neck-crepe-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Ribbed Square Neck Crepe Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-women-extended-sleeves-top",
    "name": "Women Extended Sleeves Top",
    "brand": "STREET STYLE STORE",
    "category": "Women",
    "subcategory": "Tops",
    "price": 608,
    "mrp": 1190,
    "discountPercent": 49,
    "rating": 3.9,
    "reviewCount": 352,
    "images": [
      "/img/k-fashion-women-extended-sleeves-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Women Extended Sleeves Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-women-solid-round-neck-bow-detailed-top",
    "name": "Women Solid Round Neck Bow Detailed Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 824,
    "mrp": 1450,
    "discountPercent": 43,
    "rating": 4.5,
    "reviewCount": 327,
    "images": [
      "/img/k-fashion-women-solid-round-neck-bow-detailed-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Women Solid Round Neck Bow Detailed Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-army-print-pleated-skirt",
    "name": "army print pleated skirt",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Skirts",
    "price": 661,
    "mrp": 970,
    "discountPercent": 32,
    "rating": 4.3,
    "reviewCount": 97,
    "images": [
      "/img/acubi-army-print-pleated-skirt.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "army print pleated skirt — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-black-and-wite-mesh-shirt",
    "name": "black and wite mesh shirt",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1007,
    "mrp": 1860,
    "discountPercent": 46,
    "rating": 4,
    "reviewCount": 56,
    "images": [
      "/img/acubi-black-and-wite-mesh-shirt.jpg"
    ],
    "colors": [
      "black"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "black and wite mesh shirt — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-black-cap",
    "name": "black cap",
    "brand": "ZARA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1010,
    "mrp": 1660,
    "discountPercent": 39,
    "rating": 4.1,
    "reviewCount": 51,
    "images": [
      "/img/acubi-black-cap.jpg"
    ],
    "colors": [
      "black"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "black cap — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-black-henley-top",
    "name": "black henley top",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Tops",
    "price": 442,
    "mrp": 780,
    "discountPercent": 43,
    "rating": 4.3,
    "reviewCount": 117,
    "images": [
      "/img/acubi-black-henley-top.jpg"
    ],
    "colors": [
      "black"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "black henley top — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-black-leather-boots",
    "name": "black leather boots",
    "brand": "BERSHKA",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 437,
    "mrp": 790,
    "discountPercent": 45,
    "rating": 4.3,
    "reviewCount": 197,
    "images": [
      "/img/acubi-black-leather-boots.jpg"
    ],
    "colors": [
      "black"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "black leather boots — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-black-leather-skirt",
    "name": "black leather skirt",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Skirts",
    "price": 752,
    "mrp": 1600,
    "discountPercent": 53,
    "rating": 4,
    "reviewCount": 194,
    "images": [
      "/img/acubi-black-leather-skirt.jpg"
    ],
    "colors": [
      "black"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "black leather skirt — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-black-sunglasses",
    "name": "black sunglasses",
    "brand": "ZARA",
    "category": "Accessories",
    "subcategory": "Accessories",
    "price": 430,
    "mrp": 780,
    "discountPercent": 45,
    "rating": 4,
    "reviewCount": 317,
    "images": [
      "/img/acubi-black-sunglasses.jpg"
    ],
    "colors": [
      "black"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "black sunglasses — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-cheetah-print-hat",
    "name": "cheetah print hat",
    "brand": "VERO MODA",
    "category": "Accessories",
    "subcategory": "Accessories",
    "price": 793,
    "mrp": 1170,
    "discountPercent": 32,
    "rating": 4.4,
    "reviewCount": 261,
    "images": [
      "/img/acubi-cheetah-print-hat.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "cheetah print hat — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-cropped-leather-jacket",
    "name": "cropped leather jacket",
    "brand": "VERO MODA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 943,
    "mrp": 1750,
    "discountPercent": 46,
    "rating": 3.9,
    "reviewCount": 127,
    "images": [
      "/img/acubi-cropped-leather-jacket.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "cropped leather jacket — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-dark-wash-baggy-jeans",
    "name": "dark wash baggy jeans",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 545,
    "mrp": 1050,
    "discountPercent": 48,
    "rating": 3.9,
    "reviewCount": 80,
    "images": [
      "/img/acubi-dark-wash-baggy-jeans.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "dark wash baggy jeans — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-green-full-sleeves-top",
    "name": "green full sleeves top",
    "brand": "H&M",
    "category": "Women",
    "subcategory": "Tops",
    "price": 969,
    "mrp": 1620,
    "discountPercent": 40,
    "rating": 3.9,
    "reviewCount": 347,
    "images": [
      "/img/acubi-green-full-sleeves-top.jpg"
    ],
    "colors": [
      "green"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "green full sleeves top — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-grey-pleated-skirt",
    "name": "grey pleated skirt",
    "brand": "BERSHKA",
    "category": "Women",
    "subcategory": "Skirts",
    "price": 766,
    "mrp": 1220,
    "discountPercent": 37,
    "rating": 4.5,
    "reviewCount": 56,
    "images": [
      "/img/acubi-grey-pleated-skirt.jpg"
    ],
    "colors": [
      "grey"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "grey pleated skirt — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-grey-star-beanie",
    "name": "grey star beanie",
    "brand": "ZARA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 790,
    "mrp": 1760,
    "discountPercent": 55,
    "rating": 4.5,
    "reviewCount": 231,
    "images": [
      "/img/acubi-grey-star-beanie.jpg"
    ],
    "colors": [
      "grey"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "grey star beanie — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-letterman-jacket",
    "name": "letterman jacket",
    "brand": "VERO MODA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 603,
    "mrp": 890,
    "discountPercent": 32,
    "rating": 3.9,
    "reviewCount": 377,
    "images": [
      "/img/acubi-letterman-jacket.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "letterman jacket — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-red-gingham-top",
    "name": "red gingham top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 804,
    "mrp": 1640,
    "discountPercent": 51,
    "rating": 3.9,
    "reviewCount": 251,
    "images": [
      "/img/acubi-red-gingham-top.jpg"
    ],
    "colors": [
      "red"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "red gingham top — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-white-chunky-bag",
    "name": "white chunky bag",
    "brand": "STREET STYLE STORE",
    "category": "Accessories",
    "subcategory": "Bags",
    "price": 798,
    "mrp": 1630,
    "discountPercent": 51,
    "rating": 4.3,
    "reviewCount": 397,
    "images": [
      "/img/acubi-white-chunky-bag.jpg"
    ],
    "colors": [
      "white"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "white chunky bag — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-white-graphic-tee",
    "name": "white graphic tee",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 614,
    "mrp": 970,
    "discountPercent": 37,
    "rating": 4,
    "reviewCount": 120,
    "images": [
      "/img/acubi-white-graphic-tee.jpg"
    ],
    "colors": [
      "white"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "white graphic tee — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-acubi-white-heart-cardigan",
    "name": "white heart cardigan",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 921,
    "mrp": 1540,
    "discountPercent": 40,
    "rating": 4,
    "reviewCount": 182,
    "images": [
      "/img/acubi-white-heart-cardigan.jpg"
    ],
    "colors": [
      "white"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "acubi",
      "casual"
    ],
    "description": "white heart cardigan — a must-have piece for the Acubi aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-dainty-gold-bow-charm-bracelet",
    "name": "Dainty Gold Bow Charm Bracelet",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1041,
    "mrp": 2080,
    "discountPercent": 50,
    "rating": 4.5,
    "reviewCount": 149,
    "images": [
      "/img/coquette-dainty-gold-bow-charm-bracelet.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "Dainty Gold Bow Charm Bracelet — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-deep-v-neck-cross-wrap-crop-surplice-top",
    "name": "Deep V Neck Cross Wrap Crop Surplice Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 564,
    "mrp": 870,
    "discountPercent": 35,
    "rating": 4.1,
    "reviewCount": 122,
    "images": [
      "/img/coquette-deep-v-neck-cross-wrap-crop-surplice-top.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "Deep V Neck Cross Wrap Crop Surplice Top — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-dior-vintage-coquette-heels",
    "name": "Dior vintage coquette heels",
    "brand": "FOREVER 21",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 1075,
    "mrp": 2030,
    "discountPercent": 47,
    "rating": 4.5,
    "reviewCount": 209,
    "images": [
      "/img/coquette-dior-vintage-coquette-heels.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "Dior vintage coquette heels — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-floral-print-tie-front-ruched-sweetheart-neck-cap-sleeve-crop-blouse-top",
    "name": "Floral Print Tie Front Ruched Sweetheart Neck Cap Sleeve Crop Blouse Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1014,
    "mrp": 1470,
    "discountPercent": 31,
    "rating": 4.5,
    "reviewCount": 319,
    "images": [
      "/img/coquette-floral-print-tie-front-ruched-sweetheart-neck-cap-sleeve-crop-blouse-top.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "Floral Print Tie Front Ruched Sweetheart Neck Cap Sleeve Crop Blouse Top — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-ruffle-hem-blue-jean-pleated-mini-skirt",
    "name": "Ruffle Hem Blue Jean Pleated Mini Skirt",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Skirts",
    "price": 744,
    "mrp": 1260,
    "discountPercent": 41,
    "rating": 3.9,
    "reviewCount": 71,
    "images": [
      "/img/coquette-ruffle-hem-blue-jean-pleated-mini-skirt.jpg"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "Ruffle Hem Blue Jean Pleated Mini Skirt — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-womens-floral-dress",
    "name": "Womens Floral Dress",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 617,
    "mrp": 1060,
    "discountPercent": 42,
    "rating": 4.4,
    "reviewCount": 354,
    "images": [
      "/img/coquette-womens-floral-dress.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "Womens Floral Dress — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-blue-long-sleevy-cardigan-sweater",
    "name": "blue long sleevy cardigan sweater",
    "brand": "H&M",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 709,
    "mrp": 1140,
    "discountPercent": 38,
    "rating": 4.2,
    "reviewCount": 114,
    "images": [
      "/img/coquette-blue-long-sleevy-cardigan-sweater.jpg"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "blue long sleevy cardigan sweater — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-bow-earrings",
    "name": "bow earrings",
    "brand": "STREET STYLE STORE",
    "category": "Accessories",
    "subcategory": "Jewellery",
    "price": 788,
    "mrp": 1430,
    "discountPercent": 45,
    "rating": 4.4,
    "reviewCount": 154,
    "images": [
      "/img/coquette-bow-earrings.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "bow earrings — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-cherry-red-block-heels",
    "name": "cherry red block heels",
    "brand": "VERO MODA",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 764,
    "mrp": 1590,
    "discountPercent": 52,
    "rating": 4.5,
    "reviewCount": 229,
    "images": [
      "/img/coquette-cherry-red-block-heels.jpg"
    ],
    "colors": [
      "red"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "cherry red block heels — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-floral-headband",
    "name": "floral headband",
    "brand": "STREET STYLE STORE",
    "category": "Women",
    "subcategory": "Tops",
    "price": 708,
    "mrp": 1510,
    "discountPercent": 53,
    "rating": 4.1,
    "reviewCount": 84,
    "images": [
      "/img/coquette-floral-headband.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "floral headband — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-heart-pearls-necklace",
    "name": "heart pearls necklace",
    "brand": "ONLY",
    "category": "Accessories",
    "subcategory": "Jewellery",
    "price": 432,
    "mrp": 850,
    "discountPercent": 49,
    "rating": 4.4,
    "reviewCount": 289,
    "images": [
      "/img/coquette-heart-pearls-necklace.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "heart pearls necklace — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-high-waist-leopard-swing-ruffle-frill-mini-skirt",
    "name": "high waist leopard swing ruffle frill mini skirt",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Skirts",
    "price": 421,
    "mrp": 840,
    "discountPercent": 50,
    "rating": 4.4,
    "reviewCount": 145,
    "images": [
      "/img/coquette-high-waist-leopard-swing-ruffle-frill-mini-skirt.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "high waist leopard swing ruffle frill mini skirt — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-summer-floral-cherry-cami-dress",
    "name": "summer floral cherry cami dress",
    "brand": "BERSHKA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 936,
    "mrp": 2080,
    "discountPercent": 55,
    "rating": 4.2,
    "reviewCount": 274,
    "images": [
      "/img/coquette-summer-floral-cherry-cami-dress.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "summer floral cherry cami dress — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-white-ballet-flats",
    "name": "white ballet flats",
    "brand": "ONLY",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 853,
    "mrp": 1500,
    "discountPercent": 43,
    "rating": 4.2,
    "reviewCount": 271,
    "images": [
      "/img/coquette-white-ballet-flats.jpg"
    ],
    "colors": [
      "white"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "white ballet flats — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-coquette-white-ruffle-mini-dress",
    "name": "white ruffle mini dress",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 634,
    "mrp": 1150,
    "discountPercent": 45,
    "rating": 4.3,
    "reviewCount": 192,
    "images": [
      "/img/coquette-white-ruffle-mini-dress.jpg"
    ],
    "colors": [
      "white"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "coquette",
      "casual"
    ],
    "description": "white ruffle mini dress — a must-have piece for the Coquette aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-chunky-platform-sandals",
    "name": "Chunky Platform Sandals",
    "brand": "H&M",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 330,
    "mrp": 550,
    "discountPercent": 40,
    "rating": 4.1,
    "reviewCount": 272,
    "images": [
      "/img/footwear-chunky-platform-sandals.webp"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Chunky Platform Sandals — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-earth-tone-sneakers",
    "name": "Earth tone Sneakers",
    "brand": "FOREVER 21",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 425,
    "mrp": 900,
    "discountPercent": 53,
    "rating": 4.5,
    "reviewCount": 69,
    "images": [
      "/img/footwear-earth-tone-sneakers.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Earth tone Sneakers — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-heel-sandals",
    "name": "Heel Sandals",
    "brand": "BERSHKA",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 897,
    "mrp": 1990,
    "discountPercent": 55,
    "rating": 4.1,
    "reviewCount": 89,
    "images": [
      "/img/footwear-heel-sandals.webp"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Heel Sandals — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-kick-off-sandal",
    "name": "Kick Off Sandal",
    "brand": "STREET STYLE STORE",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 889,
    "mrp": 1680,
    "discountPercent": 47,
    "rating": 4.4,
    "reviewCount": 276,
    "images": [
      "/img/footwear-kick-off-sandal.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Kick Off Sandal — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-new-balance-5series30",
    "name": "New Balance 5Series30",
    "brand": "VERO MODA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 593,
    "mrp": 1190,
    "discountPercent": 50,
    "rating": 4.5,
    "reviewCount": 290,
    "images": [
      "/img/footwear-new-balance-5series30.jpg"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "New Balance 5Series30 — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-party-stiletto-pumps",
    "name": "Party Stiletto Pumps",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Tops",
    "price": 365,
    "mrp": 790,
    "discountPercent": 54,
    "rating": 4.1,
    "reviewCount": 216,
    "images": [
      "/img/footwear-party-stiletto-pumps.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Party Stiletto Pumps — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-women-block-mary-janes-with-buckles",
    "name": "Women Block Mary Janes with Buckles",
    "brand": "BERSHKA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 576,
    "mrp": 1130,
    "discountPercent": 49,
    "rating": 3.9,
    "reviewCount": 143,
    "images": [
      "/img/footwear-women-block-mary-janes-with-buckles.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Women Block Mary Janes with Buckles — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-footwear-wrinkled-faux-leather-midi-boots",
    "name": "Wrinkled Faux Leather Midi Boots",
    "brand": "PULL&BEAR",
    "category": "Footwear",
    "subcategory": "Footwear",
    "price": 628,
    "mrp": 1050,
    "discountPercent": 40,
    "rating": 4.1,
    "reviewCount": 380,
    "images": [
      "/img/footwear-wrinkled-faux-leather-midi-boots.webp"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "6",
        "inStock": true
      },
      {
        "label": "7",
        "inStock": true
      },
      {
        "label": "8",
        "inStock": true
      },
      {
        "label": "9",
        "inStock": true
      },
      {
        "label": "10",
        "inStock": false
      }
    ],
    "occasionTags": [
      "footwear",
      "casual"
    ],
    "description": "Wrinkled Faux Leather Midi Boots — a must-have piece for the Footwear Essentials aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-amelie-driftwood-charm-boho-top",
    "name": "Amelie Driftwood Charm Boho Top",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 927,
    "mrp": 1780,
    "discountPercent": 48,
    "rating": 4.4,
    "reviewCount": 153,
    "images": [
      "/img/bohemian-amelie-driftwood-charm-boho-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Amelie Driftwood Charm Boho Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-artificial-beaded-boho-rattan-wooden-square-drop-earrings",
    "name": "Artificial Beaded Boho Rattan Wooden Square Drop Earrings",
    "brand": "FOREVER 21",
    "category": "Accessories",
    "subcategory": "Jewellery",
    "price": 664,
    "mrp": 1480,
    "discountPercent": 55,
    "rating": 4.3,
    "reviewCount": 179,
    "images": [
      "/img/bohemian-artificial-beaded-boho-rattan-wooden-square-drop-earrings.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Artificial Beaded Boho Rattan Wooden Square Drop Earrings — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-blue-white-linen-printed-jumpsuit",
    "name": "Blue & White Linen Printed Jumpsuit",
    "brand": "ZARA",
    "category": "Women",
    "subcategory": "Jumpsuits",
    "price": 950,
    "mrp": 1790,
    "discountPercent": 47,
    "rating": 4,
    "reviewCount": 314,
    "images": [
      "/img/bohemian-blue-white-linen-printed-jumpsuit.png"
    ],
    "colors": [
      "white",
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Blue & White Linen Printed Jumpsuit — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-bohemian-knotted-top",
    "name": "Bohemian Knotted Top",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Tops",
    "price": 675,
    "mrp": 1350,
    "discountPercent": 50,
    "rating": 4.1,
    "reviewCount": 290,
    "images": [
      "/img/bohemian-bohemian-knotted-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Bohemian Knotted Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-extended-sleeves-bohemian-peplum-top",
    "name": "Extended Sleeves Bohemian Peplum Top",
    "brand": "H&M",
    "category": "Women",
    "subcategory": "Tops",
    "price": 479,
    "mrp": 960,
    "discountPercent": 50,
    "rating": 4.4,
    "reviewCount": 62,
    "images": [
      "/img/bohemian-extended-sleeves-bohemian-peplum-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Extended Sleeves Bohemian Peplum Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-geometrical-shaped-drop-earrings",
    "name": "Geometrical Shaped Drop Earrings",
    "brand": "H&M",
    "category": "Accessories",
    "subcategory": "Jewellery",
    "price": 419,
    "mrp": 700,
    "discountPercent": 40,
    "rating": 4.2,
    "reviewCount": 290,
    "images": [
      "/img/bohemian-geometrical-shaped-drop-earrings.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Geometrical Shaped Drop Earrings — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-girls-floral-print-fringed-bohemian-cotton-crop-top",
    "name": "Girls Floral Print Fringed Bohemian Cotton Crop Top",
    "brand": "STREET STYLE STORE",
    "category": "Women",
    "subcategory": "Tops",
    "price": 528,
    "mrp": 1000,
    "discountPercent": 47,
    "rating": 4.3,
    "reviewCount": 170,
    "images": [
      "/img/bohemian-girls-floral-print-fringed-bohemian-cotton-crop-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Girls Floral Print Fringed Bohemian Cotton Crop Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-print-boho-cotton-top",
    "name": "Print Boho Cotton Top",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Tops",
    "price": 675,
    "mrp": 1020,
    "discountPercent": 34,
    "rating": 4.1,
    "reviewCount": 279,
    "images": [
      "/img/bohemian-print-boho-cotton-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Print Boho Cotton Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-ruffle-tank-top",
    "name": "Ruffle Tank Top",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1025,
    "mrp": 2050,
    "discountPercent": 50,
    "rating": 3.9,
    "reviewCount": 159,
    "images": [
      "/img/bohemian-ruffle-tank-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Ruffle Tank Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  }
];

export const INGESTED_HUBS: StyleHub[] = [
  {
    "id": "h9",
    "name": "Bohemian Bazaar",
    "aestheticTag": "bohemian",
    "description": "Flowing silhouettes, earthy tones, and free-spirited layering.",
    "coverImage": "/img/bohemian-hub.jpg",
    "baseViewerCount": 260,
    "memberCount": 9400,
    "trendingOutfitIds": [],
    "weeklyChallenge": "Festival Layering Look",
    "topCreators": [
      {
        "name": "@boho_soul",
        "avatar": ""
      }
    ]
  }
];
