// AUTO-GENERATED by scripts/src/ingest-style-photos.ts — do not hand-edit.
// Rerun the script to regenerate after adding/updating source photo folders.
import type { Product, StyleHub } from "./mock-data";

export const INGESTED_PRODUCTS: Product[] = [
  {
    "id": "p-y2k-angel-graphic-cotton-cami-top",
    "name": "Angel Graphic Cotton Cami Top",
    "brand": "ZARA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1120,
    "mrp": 1780,
    "discountPercent": 37,
    "rating": 4.2,
    "reviewCount": 331,
    "images": [
      "/img/y2k-angel-graphic-cotton-cami-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Angel Graphic Cotton Cami Top — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-chic-striped-mesh-sweater",
    "name": "Chic Striped Mesh Sweater",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 851,
    "mrp": 1420,
    "discountPercent": 40,
    "rating": 4.4,
    "reviewCount": 76,
    "images": [
      "/img/y2k-chic-striped-mesh-sweater.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Chic Striped Mesh Sweater — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-dianna-baggy-jeans",
    "name": "Dianna Baggy Jeans",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 2485,
    "mrp": 4440,
    "discountPercent": 44,
    "rating": 3.5,
    "reviewCount": -197,
    "images": [
      "/img/y2k-dianna-baggy-jeans.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Dianna Baggy Jeans — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-distressed-striped-sweater-with-scalf",
    "name": "Distressed Striped Sweater with Scalf",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 1284,
    "mrp": 1980,
    "discountPercent": 35,
    "rating": 4.4,
    "reviewCount": 325,
    "images": [
      "/img/y2k-distressed-striped-sweater-with-scalf.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Distressed Striped Sweater with Scalf — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-double-eyelet-belt",
    "name": "Double Eyelet Belt",
    "brand": "PULL&BEAR",
    "category": "Accessories",
    "subcategory": "Belts",
    "price": 697,
    "mrp": 1340,
    "discountPercent": 48,
    "rating": 4.3,
    "reviewCount": 180,
    "images": [
      "/img/y2k-double-eyelet-belt.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Double Eyelet Belt — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-fur-hooded-zip-up-knit-crop-cardigan",
    "name": "Fur Hooded Zip-up knit crop Cardigan",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 837,
    "mrp": 1670,
    "discountPercent": 50,
    "rating": 4.2,
    "reviewCount": 117,
    "images": [
      "/img/y2k-fur-hooded-zip-up-knit-crop-cardigan.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Fur Hooded Zip-up knit crop Cardigan — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-graphic-oversized-hoodie",
    "name": "Graphic Oversized Hoodie",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 1164,
    "mrp": 2280,
    "discountPercent": 49,
    "rating": 4.4,
    "reviewCount": 386,
    "images": [
      "/img/y2k-graphic-oversized-hoodie.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Graphic Oversized Hoodie — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-layered-drawstring-baggy-jorts",
    "name": "Layered DrawString Baggy Jorts",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 1382,
    "mrp": 2130,
    "discountPercent": 35,
    "rating": 3.9,
    "reviewCount": 93,
    "images": [
      "/img/y2k-layered-drawstring-baggy-jorts.png"
    ],
    "colors": [
      "red"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Layered DrawString Baggy Jorts — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-loose-fit-striped-drop-shoulder-top",
    "name": "Loose Fit Striped Drop Shoulder Top",
    "brand": "VERO MODA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1063,
    "mrp": 2310,
    "discountPercent": 54,
    "rating": 3.9,
    "reviewCount": 222,
    "images": [
      "/img/y2k-loose-fit-striped-drop-shoulder-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Loose Fit Striped Drop Shoulder Top — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-lucky-graphic-tee",
    "name": "Lucky Graphic tee",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Tops",
    "price": 551,
    "mrp": 920,
    "discountPercent": 40,
    "rating": 4.1,
    "reviewCount": 306,
    "images": [
      "/img/y2k-lucky-graphic-tee.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Lucky Graphic tee — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-mini-heart-hair-clip",
    "name": "Mini Heart Hair Clip",
    "brand": "FOREVER 21",
    "category": "Accessories",
    "subcategory": "Hair Accessories",
    "price": 814,
    "mrp": 1180,
    "discountPercent": 31,
    "rating": 4,
    "reviewCount": 301,
    "images": [
      "/img/y2k-mini-heart-hair-clip.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Mini Heart Hair Clip — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-oversized-graphic-v-neck-jersey",
    "name": "Oversized Graphic V Neck Jersey",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 777,
    "mrp": 1250,
    "discountPercent": 38,
    "rating": 3.8,
    "reviewCount": -300,
    "images": [
      "/img/y2k-oversized-graphic-v-neck-jersey.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Oversized Graphic V Neck Jersey — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-ribbon-halter-crop-top",
    "name": "Ribbon Halter Crop Top",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Tops",
    "price": 552,
    "mrp": 1130,
    "discountPercent": 51,
    "rating": 4,
    "reviewCount": 205,
    "images": [
      "/img/y2k-ribbon-halter-crop-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Ribbon Halter Crop Top — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-rose-washed-bag-jeans",
    "name": "Rose Washed Bag Jeans",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 1045,
    "mrp": 1580,
    "discountPercent": 34,
    "rating": 3.9,
    "reviewCount": -312,
    "images": [
      "/img/y2k-rose-washed-bag-jeans.png"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Rose Washed Bag Jeans — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-sleek-snakeskin-belt",
    "name": "Sleek Snakeskin Belt",
    "brand": "H&M",
    "category": "Accessories",
    "subcategory": "Belts",
    "price": 799,
    "mrp": 1540,
    "discountPercent": 48,
    "rating": 4.5,
    "reviewCount": 79,
    "images": [
      "/img/y2k-sleek-snakeskin-belt.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Sleek Snakeskin Belt — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-solic-pocketed-wide-fit-trousers",
    "name": "Solic Pocketed Wide Fit Trousers",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Trousers",
    "price": 2205,
    "mrp": 3940,
    "discountPercent": 44,
    "rating": 4,
    "reviewCount": 220,
    "images": [
      "/img/y2k-solic-pocketed-wide-fit-trousers.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Solic Pocketed Wide Fit Trousers — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-vintage-washed-denim-shorts",
    "name": "Vintage Washed Denim Shorts",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Shorts",
    "price": 1137,
    "mrp": 2370,
    "discountPercent": 52,
    "rating": 3.3,
    "reviewCount": -174,
    "images": [
      "/img/y2k-vintage-washed-denim-shorts.png"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Vintage Washed Denim Shorts — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-y2k-hair-claw-clip",
    "name": "Y2K Hair Claw Clip",
    "brand": "BERSHKA",
    "category": "Accessories",
    "subcategory": "Hair Accessories",
    "price": 856,
    "mrp": 1680,
    "discountPercent": 49,
    "rating": 4.2,
    "reviewCount": 132,
    "images": [
      "/img/y2k-y2k-hair-claw-clip.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "Y2K Hair Claw Clip — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-y2k-leilani-washed-jeans",
    "name": "leilani washed jeans",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 2144,
    "mrp": 3760,
    "discountPercent": 43,
    "rating": 3.8,
    "reviewCount": -162,
    "images": [
      "/img/y2k-leilani-washed-jeans.png"
    ],
    "colors": [
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "y2k",
      "casual"
    ],
    "description": "leilani washed jeans — a must-have piece for the Y2K Nostalgia aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-bow-detail-puff-blouse",
    "name": "Bow Detail Puff Blouse",
    "brand": "PULL&BEAR",
    "category": "Women",
    "subcategory": "Tops",
    "price": 867,
    "mrp": 1490,
    "discountPercent": 42,
    "rating": 3.3,
    "reviewCount": -282,
    "images": [
      "/img/k-fashion-bow-detail-puff-blouse.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Bow Detail Puff Blouse — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-checked-halter-neck-peplum-top",
    "name": "Checked Halter Neck Peplum Top",
    "brand": "MANGO",
    "category": "Women",
    "subcategory": "Tops",
    "price": 781,
    "mrp": 1390,
    "discountPercent": 44,
    "rating": 3.7,
    "reviewCount": -156,
    "images": [
      "/img/k-fashion-checked-halter-neck-peplum-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Checked Halter Neck Peplum Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-coffee-v-neck-sweatshirt",
    "name": "Coffee V-neck sweatshirt",
    "brand": "URBAN OUTFITTERS",
    "category": "Women",
    "subcategory": "Sweaters",
    "price": 1415,
    "mrp": 2830,
    "discountPercent": 50,
    "rating": 3.9,
    "reviewCount": 97,
    "images": [
      "/img/k-fashion-coffee-v-neck-sweatshirt.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Coffee V-neck sweatshirt — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-light-pink-top",
    "name": "Light Pink Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1124,
    "mrp": 1840,
    "discountPercent": 39,
    "rating": 3.8,
    "reviewCount": -252,
    "images": [
      "/img/k-fashion-light-pink-top.png"
    ],
    "colors": [
      "pink"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Light Pink Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-miri-low-rise-straight-jeans",
    "name": "Miri Low Rise Straight Jeans",
    "brand": "BERSHKA",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 1926,
    "mrp": 3780,
    "discountPercent": 49,
    "rating": 3.4,
    "reviewCount": -289,
    "images": [
      "/img/k-fashion-miri-low-rise-straight-jeans.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Miri Low Rise Straight Jeans — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-olynn-low-rise-distressed-flared-jeans",
    "name": "Olynn Low-Rise Distressed Flared Jeans",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Jeans",
    "price": 2262,
    "mrp": 4270,
    "discountPercent": 47,
    "rating": 3.4,
    "reviewCount": -253,
    "images": [
      "/img/k-fashion-olynn-low-rise-distressed-flared-jeans.png"
    ],
    "colors": [
      "red"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Olynn Low-Rise Distressed Flared Jeans — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-ribbed-square-neck-crepe-top",
    "name": "Ribbed Square Neck Crepe Top",
    "brand": "H&M",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1279,
    "mrp": 1940,
    "discountPercent": 34,
    "rating": 4.4,
    "reviewCount": 193,
    "images": [
      "/img/k-fashion-ribbed-square-neck-crepe-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Ribbed Square Neck Crepe Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-women-extended-sleeves-top",
    "name": "Women Extended Sleeves Top",
    "brand": "STREET STYLE STORE",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1058,
    "mrp": 2070,
    "discountPercent": 49,
    "rating": 3.5,
    "reviewCount": -192,
    "images": [
      "/img/k-fashion-women-extended-sleeves-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Women Extended Sleeves Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-k-fashion-women-solid-round-neck-bow-detailed-top",
    "name": "Women Solid Round Neck Bow Detailed Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 674,
    "mrp": 1180,
    "discountPercent": 43,
    "rating": 3.4,
    "reviewCount": -217,
    "images": [
      "/img/k-fashion-women-solid-round-neck-bow-detailed-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "k-fashion",
      "casual"
    ],
    "description": "Women Solid Round Neck Bow Detailed Top — a must-have piece for the K-Fashion Pop aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-amelie-driftwood-charm-boho-top",
    "name": "Amelie Driftwood Charm Boho Top",
    "brand": "ONLY",
    "category": "Women",
    "subcategory": "Tops",
    "price": 642,
    "mrp": 960,
    "discountPercent": 33,
    "rating": 4.5,
    "reviewCount": 274,
    "images": [
      "/img/boho-amelie-driftwood-charm-boho-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Amelie Driftwood Charm Boho Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-artificial-beaded-boho-rattan-wooden-square-drop-earrings",
    "name": "Artificial Beaded Boho Rattan Wooden Square Drop Earrings",
    "brand": "H&M",
    "category": "Accessories",
    "subcategory": "Jewellery",
    "price": 629,
    "mrp": 950,
    "discountPercent": 34,
    "rating": 4.5,
    "reviewCount": 215,
    "images": [
      "/img/boho-artificial-beaded-boho-rattan-wooden-square-drop-earrings.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Artificial Beaded Boho Rattan Wooden Square Drop Earrings — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-blue-white-linen-printed-jumpsuit",
    "name": "Blue & White Linen Printed Jumpsuit",
    "brand": "VERO MODA",
    "category": "Women",
    "subcategory": "Jumpsuits",
    "price": 553,
    "mrp": 950,
    "discountPercent": 42,
    "rating": 3.7,
    "reviewCount": -207,
    "images": [
      "/img/boho-blue-white-linen-printed-jumpsuit.png"
    ],
    "colors": [
      "white",
      "blue"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Blue & White Linen Printed Jumpsuit — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-bohemian-knotted-top",
    "name": "Bohemian Knotted Top",
    "brand": "STREET STYLE STORE",
    "category": "Women",
    "subcategory": "Tops",
    "price": 668,
    "mrp": 1260,
    "discountPercent": 47,
    "rating": 4.3,
    "reviewCount": 283,
    "images": [
      "/img/boho-bohemian-knotted-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Bohemian Knotted Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-extended-sleeves-bohemian-peplum-top",
    "name": "Extended Sleeves Bohemian Peplum Top",
    "brand": "BERSHKA",
    "category": "Women",
    "subcategory": "Tops",
    "price": 1296,
    "mrp": 2540,
    "discountPercent": 49,
    "rating": 4.1,
    "reviewCount": 391,
    "images": [
      "/img/boho-extended-sleeves-bohemian-peplum-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Extended Sleeves Bohemian Peplum Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-geometrical-shaped-drop-earrings",
    "name": "Geometrical Shaped Drop Earrings",
    "brand": "BERSHKA",
    "category": "Accessories",
    "subcategory": "Jewellery",
    "price": 606,
    "mrp": 1030,
    "discountPercent": 41,
    "rating": 3.8,
    "reviewCount": -254,
    "images": [
      "/img/boho-geometrical-shaped-drop-earrings.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "One Size",
        "inStock": true
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Geometrical Shaped Drop Earrings — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-girls-floral-print-fringed-bohemian-cotton-crop-top",
    "name": "Girls Floral Print Fringed Bohemian Cotton Crop Top",
    "brand": "H&M",
    "category": "Women",
    "subcategory": "Tops",
    "price": 539,
    "mrp": 790,
    "discountPercent": 32,
    "rating": 3.9,
    "reviewCount": 185,
    "images": [
      "/img/boho-girls-floral-print-fringed-bohemian-cotton-crop-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Girls Floral Print Fringed Bohemian Cotton Crop Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-print-boho-cotton-top",
    "name": "Print Boho Cotton Top",
    "brand": "STREET STYLE STORE",
    "category": "Women",
    "subcategory": "Tops",
    "price": 598,
    "mrp": 950,
    "discountPercent": 37,
    "rating": 3.6,
    "reviewCount": -227,
    "images": [
      "/img/boho-print-boho-cotton-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Print Boho Cotton Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  },
  {
    "id": "p-bohemian-ruffle-tank-top",
    "name": "Ruffle Tank Top",
    "brand": "FOREVER 21",
    "category": "Women",
    "subcategory": "Tops",
    "price": 944,
    "mrp": 1550,
    "discountPercent": 39,
    "rating": 3.8,
    "reviewCount": -88,
    "images": [
      "/img/boho-ruffle-tank-top.png"
    ],
    "colors": [
      "neutral"
    ],
    "sizes": [
      {
        "label": "XS",
        "inStock": true
      },
      {
        "label": "S",
        "inStock": true
      },
      {
        "label": "M",
        "inStock": true
      },
      {
        "label": "L",
        "inStock": true
      },
      {
        "label": "XL",
        "inStock": false
      }
    ],
    "occasionTags": [
      "bohemian",
      "casual"
    ],
    "description": "Ruffle Tank Top — a must-have piece for the Bohemian Bazaar aesthetic. (auto-generated, review before demo)",
    "deliveryEstimate": "2-4 business days"
  }
];

export const INGESTED_HUBS: StyleHub[] = [
  {
    "id": "h9",
    "name": "Bohemian Bazaar",
    "aestheticTag": "bohemian",
    "description": "Flowing silhouettes, earthy tones, and free-spirited layering.",
    "coverImage": "/img/bohemian-hub.jpg",
    "baseViewerCount": 260,
    "memberCount": 9400,
    "trendingOutfitIds": [],
    "weeklyChallenge": "Festival Layering Look",
    "topCreators": [
      {
        "name": "@boho_soul",
        "avatar": ""
      }
    ]
  }
];
